// Başarımlar Tanımları
export const ACHIEVEMENTS = {
  first_100: {
    key: 'first_100',
    title: 'İlk Adım',
    description: 'Allah\'ın rızasını kazanmak için ilk 100 zikir',
    icon: '🌱',
    condition: (stats) => stats.total >= 100,
  },
  first_1000: {
    key: 'first_1000',
    title: 'Zikir Ehli',
    description: '1000 zikir ile kalbin nurlanması',
    icon: '✨',
    condition: (stats) => stats.total >= 1000,
  },
  streak_7: {
    key: 'streak_7',
    title: 'Haftalık İbadet',
    description: '7 gün boyunca devamlılık göstermek',
    icon: '🕌',
    condition: (stats) => stats.streak >= 7,
  },
  streak_30: {
    key: 'streak_30',
    title: 'Aylık Sebat',
    description: '30 gün boyunca Allah\'ı zikretmek',
    icon: '🌙',
    condition: (stats) => stats.streak >= 30,
  },
  perfect_day: {
    key: 'perfect_day',
    title: 'Mübarek Gün',
    description: 'Bir günde 500+ defa Allah\'ı anmak',
    icon: '☀️',
    condition: (stats) => stats.bestDay && stats.bestDay.total >= 500,
  },
  all_targets: {
    key: 'all_targets',
    title: 'Niyet Sahibi',
    description: 'Tüm hedefleri samimiyetle tamamlamak',
    icon: '🎯',
    condition: (stats) => stats.completedTargets >= 5,
  },
  first_10000: {
    key: 'first_10000',
    title: 'Kalbin Nurlanması',
    description: '10,000 zikirle kalbi aydınlatmak',
    icon: '💫',
    condition: (stats) => stats.total >= 10000,
  },
  first_50000: {
    key: 'first_50000',
    title: 'Zikir Deryası',
    description: '50,000 zikirle maneviyat denizine dalmak',
    icon: '🌊',
    condition: (stats) => stats.total >= 50000,
  },
  streak_100: {
    key: 'streak_100',
    title: 'Devamlı Kullar',
    description: '100 gün boyunca Allah ile beraber olmak',
    icon: '⭐',
    condition: (stats) => stats.streak >= 100,
  },
  streak_365: {
    key: 'streak_365',
    title: 'Yılın Sadık Kulu',
    description: '365 gün aralıksız Allah\'ı zikretmek',
    icon: '👑',
    condition: (stats) => stats.streak >= 365,
  },
  marathon: {
    key: 'marathon',
    title: 'Gönül Serveti',
    description: 'Bir günde 1000+ zikir ile zenginleşmek',
    icon: '💎',
    condition: (stats) => stats.bestDay && stats.bestDay.total >= 1000,
  },
  consistency_king: {
    key: 'consistency_king',
    title: 'Sabırlı Mü\'min',
    description: '14 gün istikrarla ibadete devam etmek',
    icon: '🕊️',
    condition: (stats) => stats.streak >= 14,
  },
  dedication: {
    key: 'dedication',
    title: 'Muhlis Kul',
    description: '50 gün samimiyetle zikirde olmak',
    icon: '🤲',
    condition: (stats) => stats.streak >= 50,
  },
  first_week: {
    key: 'first_week',
    title: 'İbadet Kapısı',
    description: '7 gün zikir kapısından girmek',
    icon: '🚪',
    condition: (stats) => stats.days >= 7,
  },
  first_month: {
    key: 'first_month',
    title: 'Manevi Yolculuk',
    description: '30 gün maneviyat yolunda ilerlemek',
    icon: '🛤️',
    condition: (stats) => stats.days >= 30,
  },
  first_100_days: {
    key: 'first_100_days',
    title: 'Daimi Zikir',
    description: '100 gün zikir yolunda yürümek',
    icon: '🌟',
    condition: (stats) => stats.days >= 100,
  },
  daily_master: {
    key: 'daily_master',
    title: 'Gönül Dostları',
    description: 'Her gün ortalama 200+ zikir ile hatırlamak',
    icon: '💝',
    condition: (stats) => stats.avgDaily >= 200,
  },
  super_daily: {
    key: 'super_daily',
    title: 'Veliler Sofrasında',
    description: 'Her gün ortalama 500+ zikir ile yükselmek',
    icon: '🌺',
    condition: (stats) => stats.avgDaily >= 500,
  },
};

