// Günlük Hadisler (Çok Dilli)
const hadiths = {
  tr: [
    { text: "Allah'ın en çok sevdiği amel, az da olsa devamlı olanıdır.", source: "Buhari, Müslim" },
    { text: "İman yetmiş küsur şubedir. En üstünü 'La ilahe illallah' demek, en altı ise yoldan rahatsızlık veren şeyi kaldırmaktır.", source: "Buhari, Müslim" },
    { text: "Mümin, mümine karşı bir binanın tuğlaları gibidir. Birbirini sıkıca tutar.", source: "Buhari" },
    { text: "Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe gerçek anlamda iman etmiş olmaz.", source: "Buhari, Müslim" },
    { text: "Allah, sizin dış görünüşünüze ve mallarınıza bakmaz. O, kalplerinize ve amellerinize bakar.", source: "Müslim" },
    { text: "İnsanların en hayırlısı, insanlara en çok faydalı olandır.", source: "Taberani" },
    { text: "Kolaylaştırın, zorlaştırmayın. Müjdeleyin, nefret ettirmeyin.", source: "Buhari" },
    { text: "Allah'ın rızası, anne-babanın rızasındadır. Allah'ın gazabı da anne-babanın gazabındadır.", source: "Tirmizi" },
    { text: "Temizlik imanın yarısıdır.", source: "Müslim" },
    { text: "Sabır, imanın yarısıdır.", source: "Tirmizi" },
    { text: "İlim öğrenmek, her Müslüman erkek ve kadına farzdır.", source: "İbn Mace" },
    { text: "İki kişi arasında adaletle hükmetmek sadakadır.", source: "Buhari, Müslim" },
    { text: "Güzel söz sadakadır.", source: "Buhari, Müslim" },
    { text: "Yoldan rahatsızlık veren bir şeyi kaldırmak sadakadır.", source: "Buhari, Müslim" },
    { text: "Mümin, aynı delikten iki kez sokulmaz.", source: "Buhari, Müslim" },
    { text: "Mümin, başkalarıyla iyi geçinen ve kendisiyle iyi geçinilen kimsedir.", source: "Tirmizi" },
    { text: "Allah'ın en çok sevdiği kul, ailesine en çok faydalı olandır.", source: "Tirmizi" },
    { text: "En hayırlınız, Kur'an'ı öğrenen ve öğretendir.", source: "Buhari" },
    { text: "İnsanların en hayırlısı, ömrü uzun, ameli güzel olandır.", source: "Tirmizi" },
    { text: "Allah, sizin bedenlerinize ve suretlerinize bakmaz, kalplerinize ve amellerinize bakar.", source: "Müslim" },
    { text: "Mümin, mümine karşı bir binanın tuğlaları gibidir.", source: "Buhari" },
    { text: "İman yetmiş küsur şubedir. Haya da imanın bir şubesidir.", source: "Buhari, Müslim" },
    { text: "Allah'ın en çok sevdiği amel, az da olsa devamlı olanıdır.", source: "Buhari, Müslim" },
    { text: "Mümin, mümine karşı bir binanın tuğlaları gibidir. Birbirini sıkıca tutar.", source: "Buhari" },
    { text: "Sizden biriniz, kendisi için istediğini kardeşi için de istemedikçe gerçek anlamda iman etmiş olmaz.", source: "Buhari, Müslim" },
    { text: "Allah, sizin dış görünüşünüze ve mallarınıza bakmaz. O, kalplerinize ve amellerinize bakar.", source: "Müslim" },
    { text: "İnsanların en hayırlısı, insanlara en çok faydalı olandır.", source: "Taberani" },
    { text: "Kolaylaştırın, zorlaştırmayın. Müjdeleyin, nefret ettirmeyin.", source: "Buhari" },
    { text: "Allah'ın rızası, anne-babanın rızasındadır. Allah'ın gazabı da anne-babanın gazabındadır.", source: "Tirmizi" },
    { text: "Temizlik imanın yarısıdır.", source: "Müslim" },
  ],
  en: [
    { text: "The most beloved deed to Allah is the one that is consistent, even if it is small.", source: "Bukhari, Muslim" },
    { text: "Faith has over seventy branches. The highest is saying 'La ilaha illallah' and the lowest is removing something harmful from the road.", source: "Bukhari, Muslim" },
    { text: "A believer to another believer is like a building whose different parts enforce each other.", source: "Bukhari" },
    { text: "None of you truly believes until he wishes for his brother what he wishes for himself.", source: "Bukhari, Muslim" },
    { text: "Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.", source: "Muslim" },
    { text: "The best of people are those who are most beneficial to others.", source: "Tabarani" },
    { text: "Make things easy, do not make them difficult. Give glad tidings, do not repel people.", source: "Bukhari" },
    { text: "Allah's pleasure is in the pleasure of parents, and Allah's displeasure is in the displeasure of parents.", source: "Tirmidhi" },
    { text: "Cleanliness is half of faith.", source: "Muslim" },
    { text: "Patience is half of faith.", source: "Tirmidhi" },
    { text: "Seeking knowledge is obligatory upon every Muslim, male and female.", source: "Ibn Majah" },
    { text: "Judging justly between two people is charity.", source: "Bukhari, Muslim" },
    { text: "A good word is charity.", source: "Bukhari, Muslim" },
    { text: "Removing something harmful from the road is charity.", source: "Bukhari, Muslim" },
    { text: "A believer is not stung from the same hole twice.", source: "Bukhari, Muslim" },
    { text: "A believer is one who gets along with others and others get along with him.", source: "Tirmidhi" },
    { text: "The most beloved of people to Allah is the one who is most beneficial to his family.", source: "Tirmidhi" },
    { text: "The best among you are those who learn the Quran and teach it.", source: "Bukhari" },
    { text: "The best of people are those whose lives are long and whose deeds are good.", source: "Tirmidhi" },
    { text: "Allah does not look at your bodies or your appearances, but He looks at your hearts and your deeds.", source: "Muslim" },
    { text: "A believer to another believer is like a building whose different parts enforce each other.", source: "Bukhari" },
    { text: "Faith has over seventy branches. Modesty is a branch of faith.", source: "Bukhari, Muslim" },
    { text: "The most beloved deed to Allah is the one that is consistent, even if it is small.", source: "Bukhari, Muslim" },
    { text: "A believer to another believer is like a building whose different parts enforce each other.", source: "Bukhari" },
    { text: "None of you truly believes until he wishes for his brother what he wishes for himself.", source: "Bukhari, Muslim" },
    { text: "Allah does not look at your appearance or your wealth, but He looks at your hearts and your deeds.", source: "Muslim" },
    { text: "The best of people are those who are most beneficial to others.", source: "Tabarani" },
    { text: "Make things easy, do not make them difficult. Give glad tidings, do not repel people.", source: "Bukhari" },
    { text: "Allah's pleasure is in the pleasure of parents, and Allah's displeasure is in the displeasure of parents.", source: "Tirmidhi" },
    { text: "Cleanliness is half of faith.", source: "Muslim" },
  ],
  ar: [
    { text: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ", source: "البخاري ومسلم" },
    { text: "الإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً، أَعْلاهَا قَوْلُ لا إِلَهَ إِلا اللَّهُ، وَأَدْنَاهَا إِمَاطَةُ الأَذَى عَنِ الطَّرِيقِ", source: "البخاري ومسلم" },
    { text: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا", source: "البخاري" },
    { text: "لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", source: "البخاري ومسلم" },
    { text: "إِنَّ اللَّهَ لا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ", source: "مسلم" },
    { text: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", source: "الطبراني" },
    { text: "يَسِّرُوا وَلا تُعَسِّرُوا، وَبَشِّرُوا وَلا تُنَفِّرُوا", source: "البخاري" },
    { text: "رِضَا اللَّهِ فِي رِضَا الْوَالِدَيْنِ، وَسَخَطُ اللَّهِ فِي سَخَطِ الْوَالِدَيْنِ", source: "الترمذي" },
    { text: "الطُّهُورُ شَطْرُ الإِيمَانِ", source: "مسلم" },
    { text: "الصَّبْرُ شَطْرُ الإِيمَانِ", source: "الترمذي" },
    { text: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ", source: "ابن ماجه" },
    { text: "الْعَدْلُ بَيْنَ اثْنَيْنِ صَدَقَةٌ", source: "البخاري ومسلم" },
    { text: "الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ", source: "البخاري ومسلم" },
    { text: "إِمَاطَةُ الأَذَى عَنِ الطَّرِيقِ صَدَقَةٌ", source: "البخاري ومسلم" },
    { text: "لا يُلْدَغُ الْمُؤْمِنُ مِنْ جُحْرٍ وَاحِدٍ مَرَّتَيْنِ", source: "البخاري ومسلم" },
    { text: "الْمُؤْمِنُ مَنْ أَمِنَهُ النَّاسُ عَلَى أَمْوَالِهِمْ وَأَنْفُسِهِمْ", source: "الترمذي" },
    { text: "أَحَبُّ النَّاسِ إِلَى اللَّهِ أَنْفَعُهُمْ لِأَهْلِهِ", source: "الترمذي" },
    { text: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ", source: "البخاري" },
    { text: "خَيْرُ النَّاسِ مَنْ طَالَ عُمُرُهُ وَحَسُنَ عَمَلُهُ", source: "الترمذي" },
    { text: "إِنَّ اللَّهَ لا يَنْظُرُ إِلَى أَجْسَامِكُمْ وَلا إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ", source: "مسلم" },
    { text: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا", source: "البخاري" },
    { text: "الإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً، وَالْحَيَاءُ شُعْبَةٌ مِنَ الإِيمَانِ", source: "البخاري ومسلم" },
    { text: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ", source: "البخاري ومسلم" },
    { text: "الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا", source: "البخاري" },
    { text: "لا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", source: "البخاري ومسلم" },
    { text: "إِنَّ اللَّهَ لا يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ", source: "مسلم" },
    { text: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ", source: "الطبراني" },
    { text: "يَسِّرُوا وَلا تُعَسِّرُوا، وَبَشِّرُوا وَلا تُنَفِّرُوا", source: "البخاري" },
    { text: "رِضَا اللَّهِ فِي رِضَا الْوَالِدَيْنِ، وَسَخَطُ اللَّهِ فِي سَخَطِ الْوَالِدَيْنِ", source: "الترمذي" },
    { text: "الطُّهُورُ شَطْرُ الإِيمَانِ", source: "مسلم" },
  ],
};

// Günün hadisini döndüren fonksiyon
export const getDailyHadith = (language = 'tr') => {
  const startDate = new Date('2024-01-01');
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const diffTime = today - startDate;
  const diffDays = Math.floor(diffTime / (1000 * 60 * 60 * 24));
  const dayOfYear = (diffDays % 365) + 1;
  
  const currentHadiths = hadiths[language] || hadiths.tr;
  const hadithIndex = (dayOfYear - 1) % currentHadiths.length;
  return currentHadiths[hadithIndex];
};

