// Tema Tanımları
export const themes = {
  dark: {
    name: 'Koyu Tema',
    description: 'Klasik koyu tema',
    colors: {
      background: '#0f172a',
      surface: '#1e293b',
      surfaceLight: '#334155',
      primary: '#6366f1',
      primaryLight: '#818cf8',
      text: '#ffffff',
      textSecondary: '#e2e8f0',
      textMuted: '#94a3b8',
      border: '#334155',
      accent: '#6366f1',
    },
  },
  green: {
    name: 'Yeşil Tema',
    description: 'İslami yeşil tema',
    colors: {
      background: '#0a1f0a',
      surface: '#1a3a1a',
      surfaceLight: '#2d4d2d',
      primary: '#22c55e',
      primaryLight: '#4ade80',
      text: '#ffffff',
      textSecondary: '#d1fae5',
      textMuted: '#86efac',
      border: '#2d4d2d',
      accent: '#22c55e',
    },
  },
  gold: {
    name: 'Altın Tema',
    description: 'Lüks altın tema',
    colors: {
      background: '#1a1a0a',
      surface: '#2d2d1a',
      surfaceLight: '#3d3d2a',
      primary: '#fbbf24',
      primaryLight: '#fcd34d',
      text: '#ffffff',
      textSecondary: '#fef3c7',
      textMuted: '#fde68a',
      border: '#3d3d2a',
      accent: '#fbbf24',
    },
  },
  blue: {
    name: 'Mavi Tema',
    description: 'Sakin mavi tema',
    colors: {
      background: '#0a1a2a',
      surface: '#1a2a3a',
      surfaceLight: '#2a3a4a',
      primary: '#3b82f6',
      primaryLight: '#60a5fa',
      text: '#ffffff',
      textSecondary: '#dbeafe',
      textMuted: '#93c5fd',
      border: '#2a3a4a',
      accent: '#3b82f6',
    },
  },
  purple: {
    name: 'Mor Tema',
    description: 'Modern mor tema',
    colors: {
      background: '#1a0a2a',
      surface: '#2a1a3a',
      surfaceLight: '#3a2a4a',
      primary: '#a855f7',
      primaryLight: '#c084fc',
      text: '#ffffff',
      textSecondary: '#f3e8ff',
      textMuted: '#d8b4fe',
      border: '#3a2a4a',
      accent: '#a855f7',
    },
  },
};

