// Zikir Listesi - 30 Önerilen Zikir
export const ZIKIR_LIST = [
  { id: 1, name: 'Subhanallah', arabic: 'سُبْحَانَ اللَّهِ' },
  { id: 2, name: 'Elhamdülillah', arabic: 'الْحَمْدُ لِلَّهِ' },
  { id: 3, name: 'Allahu Ekber', arabic: 'اللَّهُ أَكْبَرُ' },
  { id: 4, name: 'La ilahe illallah', arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ' },
  { id: 5, name: 'Subhanallahi ve bihamdihi', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ' },
  { id: 6, name: 'Subhanallahi\'l-azim', arabic: 'سُبْحَانَ اللَّهِ الْعَظِيمِ' },
  { id: 7, name: 'La havle ve la kuvvete illa billah', arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ' },
  { id: 8, name: 'Hasbunallahu ve ni\'mel vekil', arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ' },
  { id: 9, name: 'Astagfirullah', arabic: 'أَسْتَغْفِرُ اللَّهَ' },
  { id: 10, name: 'La ilahe illa ente subhaneke', arabic: 'لَا إِلَٰهَ إِلَّا أَنْتَ سُبْحَانَكَ' },
  { id: 11, name: 'Subhanallahi ve bihamdihi subhanallahi\'l-azim', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ' },
  { id: 12, name: 'Rabbena atina fid-dunya haseneten', arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً' },
  { id: 13, name: 'Rabbenağfirli', arabic: 'رَبَّنَا اغْفِرْ لِي' },
  { id: 14, name: 'Allahumme salli ala Muhammed', arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ' },
  { id: 15, name: 'Allahumme barik ala Muhammed', arabic: 'اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ' },
  { id: 16, name: 'Subhanallahi ve bihamdihi adede halkihi', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ عَدَدَ خَلْقِهِ' },
  { id: 17, name: 'La ilahe illallahu vahdehu la şerike leh', arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ' },
  { id: 18, name: 'Allahumme inni es\'eluke\'l-afiyete', arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ' },
  { id: 19, name: 'Hasbiyallahu la ilahe illa hu', arabic: 'حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ' },
  { id: 20, name: 'Subhanallahi ve bihamdihi subhanallahi\'l-azim', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ' },
  { id: 21, name: 'Allahumme inni e\'uzu bike min şerri nefsi', arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي' },
  { id: 22, name: 'Rabbena la tuziğ kulubena', arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا' },
  { id: 23, name: 'Subhanallahi\'l-aliyyi\'l-azim', arabic: 'سُبْحَانَ اللَّهِ الْعَلِيِّ الْعَظِيمِ' },
  { id: 24, name: 'Allahumme inni es\'eluke\'l-cennete', arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ' },
  { id: 25, name: 'La ilahe illallahu Muhammedun resulullah', arabic: 'لَا إِلَٰهَ إِلَّا اللَّهُ مُحَمَّدٌ رَسُولُ اللَّهِ' },
  { id: 26, name: 'Subhanallahi ve bihamdihi subhanallahi\'l-azim ve bihamdihi', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ وَبِحَمْدِهِ' },
  { id: 27, name: 'Allahumme inni es\'eluke\'l-huda', arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى' },
  { id: 28, name: 'Rabbena hablana min ezvacina', arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا' },
  { id: 29, name: 'Subhanallahi ve bihamdihi subhanallahi\'l-azim', arabic: 'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ سُبْحَانَ اللَّهِ الْعَظِيمِ' },
  { id: 30, name: 'Allahumme inni es\'eluke\'r-rizka\'t-tayyib', arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الرِّزْقَ الطَّيِّبَ' },
];

